# Clean STCPv2 Zephyr adapter
CONFIG_STCP=n
CONFIG_STCP_V2=y

# IMPORTANT: do not enable global socket offload just for AF_STCP.
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=n
CONFIG_NET_NATIVE=y
CONFIG_NET_NATIVE_IP=y
CONFIG_NET_NATIVE_IPV4=y
CONFIG_NET_NATIVE_TCP=y
CONFIG_NET_NATIVE_UDP=y
CONFIG_NET_ARP=y

CONFIG_STCP_V2_TRACE_WIRE=n
CONFIG_STCP_V2_TRACE_EVENTS=n
CONFIG_STCP_V2_TRACE_ALLOC=n
CONFIG_STCP_V2_TRACE_CRYPTO=n
