/* AUTOGENERATED: DO NOT MODIFY! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void *stcp_server_bind(const uint8_t *ip_ptr,
                       uintptr_t ip_len,
                       uint16_t port,
                       ServerMessageProcessCB cb);

int32_t stcp_server_listen(void *server_ptr);

void stcp_server_stop(void *server_ptr);
