# nRF9151 LTE transport only.

# Modem socket offload; no Zephyr native IP stack.
CONFIG_NET_NATIVE=n
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_IPV6=y

# nRF91 modem / LTE
CONFIG_NRF_MODEM_LIB=y
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_LC_PDN_MODULE=y
CONFIG_LTE_NETWORK_MODE_LTE_M=y
CONFIG_LTE_PSM_REQ=n
CONFIG_LTE_EDRX_REQ=n
CONFIG_UART_NRFX=y

# LTE transport
CONFIG_STCP_LTE_REG_TIMEOUT_SECONDS=300
CONFIG_STCP_LTE_PDN_TIMEOUT_SECONDS=300
CONFIG_STCP_LTE_FORCE_DEFAULT_APN=y
CONFIG_STCP_LTE_DEFAULT_APN="internet"
CONFIG_STCP_LTE_CUSTOM_PDN=y
CONFIG_STCP_LTE_APN="internet"

# LTE memory budget
CONFIG_HEAP_MEM_POOL_SIZE=65536
