#!/bin/bash
set -euo pipefail

echo "🔧 Settingup toolchain variables with PROJECT_ROOT as ${PROJECT_ROOT} ..."


# Tämä ohittaa glibc- ja musl-crossit

export TOOLCHAIN="/home/pomo/zephyr-sdk-0.17.1"
export TOOLCHAIN_TARGET="arm-zephyr-eabi" 

export TOOLCHAIN_CC=$TOOLCHAIN/${TOOLCHAIN_TARGET}-gcc
export TOOLCHAIN_CXX=$TOOLCHAIN/${TOOLCHAIN_TARGET}-g++
export TOOLCHAIN_LD=$TOOLCHAIN/${TOOLCHAIN_TARGET}-ld
export TOOLCHAIN_AR=$TOOLCHAIN/${TOOLCHAIN_TARGET}-ar
export TOOLCHAIN_RANLIB=$TOOLCHAIN/${TOOLCHAIN_TARGET}-ranlib
export TOOLCHAIN_NM=$TOOLCHAIN/${TOOLCHAIN_TARGET}-nm

export PATH="$TOOLCHAIN/bin:$HOME/.cargo/bin:$PATH"

echo "🔧 Asennettu toolchain muuttujat OK"

