message(STATUS "STCP MQTT sysbuild: DEFAULT_IMAGE=${DEFAULT_IMAGE}")

set_config_bool(${DEFAULT_IMAGE} CONFIG_MQTT_LIB ON)
set_config_bool(${DEFAULT_IMAGE} CONFIG_MQTT_LIB_CUSTOM_TRANSPORT ON)
set_config_bool(${DEFAULT_IMAGE} CONFIG_MQTT_VERSION_3_1_1 ON)
set_config_int(${DEFAULT_IMAGE} CONFIG_MQTT_KEEPALIVE 60)

get_property(STCP_MQTT_IMAGE_CONFIG
             TARGET ${DEFAULT_IMAGE}
             PROPERTY CONFIG)

message(STATUS "STCP MQTT image CONFIG >>>")
message(STATUS "${STCP_MQTT_IMAGE_CONFIG}")
message(STATUS "<<< STCP MQTT image CONFIG")

