/* AUTOGENERATED: DO NOT MODIFY! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void (*ServerMessageProcessCB)(const uint8_t *input_ptr,
                                       uintptr_t input_len,
                                       uint8_t *output_buf,
                                       uintptr_t max_output_len,
                                       uintptr_t *actual_output_len);

void *stcp_server_bind(const uint8_t *ip_ptr,
                       uintptr_t ip_len,
                       uint16_t port,
                       ServerMessageProcessCB cb);

int32_t stcp_server_listen(void *server_ptr);

void stcp_server_stop(void *server_ptr);
