#!/bin/bash
set -e
echo Torture
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-torture-server

echo Proxy
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-proxy

echo PlainProxy
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-to-plain-proxy

echo STCPProxy
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-to-stcp-proxy

echo GW
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-gateway

echo server
cargo +nightly build --features stcp_debug,linux --manifest-path ./Cargo.toml --bin stcp-server


