#!/bin/bash
set -e

export CMAKE_MAKE_PROGRAM=/usr/bin/ninja
export NINJA=/usr/bin/ninja
export ZEPHYR_EXTRA_MODULES=/home/pomo/ncs/stcp-modeemi/moduuli-tcp

  west build -p ${1:-always} -b nrf9151dk/nrf9151/ns  -d build -- \
    -DJLINK_DEVICE=NRF9151_XXCA \
    -DJLINK_TOOL_OPT=-USB=1052094012 \
    -DSTCP_DEBUG=1

   west flash -d ./build --runner jlink --file ./build/merged.hex -- \
    --device NRF9151_XXCA \
    --tool-opt=-USB \
    --tool-opt=1052094012

pncnote "STCP kääntyö" "Dodii nyt ois valmista"
