.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xde0
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xde8
.global __hyp_section_.hyp.text
.global __hyp_section_.hyp.rodata
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x518
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5a0
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5a8
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e0
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x600
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x618
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x680
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x6f8
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x718
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7a0
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7a8
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x7e0
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x800
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x818
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x880
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xca8
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcb0
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcb8
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcc0
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcc8
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcd0
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcd8
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xce0
.word 0
.reloc 100, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xce8
.word 0
.reloc 104, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcf0
.word 0
.reloc 108, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xcf8
.word 0
.reloc 112, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd00
.word 0
.reloc 116, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd08
.word 0
.reloc 120, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd10
.word 0
.reloc 124, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd18
.word 0
.reloc 128, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd20
.word 0
.reloc 132, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd28
.word 0
.reloc 136, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd30
.word 0
.reloc 140, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd38
.word 0
.reloc 144, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd40
.word 0
.reloc 148, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd48
.word 0
.reloc 152, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd50
.word 0
.reloc 156, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd58
.word 0
.reloc 160, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd60
.word 0
.reloc 164, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd68
.word 0
.reloc 168, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd70
.word 0
.reloc 172, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd78
.word 0
.reloc 176, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd80
.word 0
.reloc 180, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd88
.word 0
.reloc 184, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd90
.word 0
.reloc 188, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xd98
.word 0
.reloc 192, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xda0
.word 0
.reloc 196, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xda8
.word 0
.reloc 200, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xdb0
.word 0
.reloc 204, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xfb0
.word 0
.reloc 208, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xfb8
.word 0
.reloc 212, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2488
.word 0
.reloc 216, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2538
.word 0
.reloc 220, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2548
.word 0
.reloc 224, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2618
.word 0
.reloc 228, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2628
.word 0
.reloc 232, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27d0
.word 0
.reloc 236, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2820
.word 0
.reloc 240, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2838
.word 0
.reloc 244, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2870
.word 0
.reloc 248, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2888
.word 0
.reloc 252, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28c0
.word 0
.reloc 256, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28d8
.word 0
.reloc 260, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2910
.word 0
.reloc 264, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2928
.word 0
.reloc 268, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2960
.word 0
.reloc 272, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2978
.word 0
.reloc 276, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29b0
.word 0
.reloc 280, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29c8
.word 0
.reloc 284, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a00
.word 0
.reloc 288, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a18
.word 0
.reloc 292, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a50
.word 0
.reloc 296, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a68
.word 0
.reloc 300, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2aa0
.word 0
.reloc 304, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ab8
.word 0
.reloc 308, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2af0
.word 0
.reloc 312, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b08
.word 0
.reloc 316, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b40
.word 0
.reloc 320, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b58
.word 0
.reloc 324, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b90
.word 0
.reloc 328, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ba8
.word 0
.reloc 332, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2be0
.word 0
.reloc 336, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2bf8
.word 0
.reloc 340, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c30
.word 0
.reloc 344, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c48
.word 0
.reloc 348, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c80
.word 0
.reloc 352, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c98
.word 0
.reloc 356, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cd0
.word 0
.reloc 360, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ce8
.word 0
.reloc 364, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d20
.word 0
.reloc 368, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d38
.word 0
.reloc 372, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d70
.word 0
.reloc 376, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d88
.word 0
.reloc 380, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2dc0
.word 0
.reloc 384, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2dd8
.word 0
.reloc 388, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e28
.word 0
.reloc 392, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e60
.word 0
.reloc 396, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e78
.word 0
.reloc 400, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2eb0
.word 0
.reloc 404, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ec8
.word 0
.reloc 408, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f00
.word 0
.reloc 412, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f18
.word 0
.reloc 416, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f68
.word 0
.reloc 420, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fa0
.word 0
.reloc 424, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fb8
.word 0
.reloc 428, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ff0
.word 0
.reloc 432, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3008
.word 0
.reloc 436, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3058
.word 0
.reloc 440, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30a8
.word 0
.reloc 444, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30e0
.word 0
.reloc 448, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30f8
.word 0
.reloc 452, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3148
.word 0
.reloc 456, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3198
.word 0
.reloc 460, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x31e8
.word 0
.reloc 464, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3220
.word 0
.reloc 468, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3238
.word 0
.reloc 472, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3270
.word 0
.reloc 476, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3288
.word 0
.reloc 480, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x32d8
.word 0
.reloc 484, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3328
.word 0
.reloc 488, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3360
.word 0
.reloc 492, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3378
.word 0
.reloc 496, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x33b0
.word 0
.reloc 500, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x33c8
.word 0
.reloc 504, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3418
.word 0
.reloc 508, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3468
.word 0
.reloc 512, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x34a0
.word 0
.reloc 516, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x34b8
.word 0
.reloc 520, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x34f0
.word 0
.reloc 524, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3508
.word 0
.reloc 528, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3540
.word 0
.reloc 532, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3558
.word 0
.reloc 536, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x35a8
.word 0
.reloc 540, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x35f8
.word 0
.reloc 544, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3648
.word 0
.reloc 548, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3698
.word 0
.reloc 552, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x36e8
.word 0
.reloc 556, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3720
.word 0
.reloc 560, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3738
.word 0
.reloc 564, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3770
.word 0
.reloc 568, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3788
.word 0
.reloc 572, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x37c0
.word 0
.reloc 576, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x37d8
.word 0
.reloc 580, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3828
.word 0
.reloc 584, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3878
.word 0
.reloc 588, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x38c8
.word 0
.reloc 592, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3918
.word 0
.reloc 596, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3968
.word 0
.reloc 600, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x39a0
.word 0
.reloc 604, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x39b8
.word 0
.reloc 608, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x39f0
.word 0
.reloc 612, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3a08
.word 0
.reloc 616, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3a40
.word 0
.reloc 620, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3a58
.word 0
.reloc 624, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3a90
.word 0
.reloc 628, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3aa8
.word 0
.reloc 632, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3ae0
.word 0
.reloc 636, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3af8
.word 0
.reloc 640, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3b30
.word 0
.reloc 644, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3b48
.word 0
.reloc 648, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3b80
.word 0
.reloc 652, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3b98
.word 0
.reloc 656, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3bd0
.word 0
.reloc 660, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3be8
.word 0
.reloc 664, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3c20
.word 0
.reloc 668, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3c70
.word 0
.reloc 672, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3cc0
.word 0
.reloc 676, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3d10
.word 0
.reloc 680, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3d28
.word 0
.reloc 684, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3d60
.word 0
.reloc 688, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3db0
.word 0
.reloc 692, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3e00
.word 0
.reloc 696, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3e50
.word 0
.reloc 700, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3ea0
.word 0
.reloc 704, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3ef0
.word 0
.reloc 708, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3f40
.word 0
.reloc 712, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3f90
.popsection
