language = "C"
pragma_once = true

include_guard = "STCP_H"
style = "both"

[parse]
parse_deps = false
include = ["the_stcp_kernel_module"]

[export]
item_types = ["functions", "structs", "enums", "typedefs", "constants"]
include = ["stcp_.*", "zsock_.*"]
exclude = ["StcpAesCodec"]

[defines]
"target_os = linux" = "STCP_LINUX"
"target_os = none"  = "STCP_ZEPHYR"

