/* AUTOGENERATED: DO NOT MODIFY! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void (*ServerMessageProcessCB)(const uint8_t *input_ptr,
                                       uintptr_t input_len,
                                       uint8_t *output_buf,
                                       uintptr_t max_output_len,
                                       uintptr_t *actual_output_len);
