#pragma once

enum mqtt_state {
    MQTT_STATE_INITIAL,
    MQTT_STATE_IDLE,
    MQTT_STATE_CONNECT,
    MQTT_STATE_SUBSCRIBE,
    MQTT_STATE_RUNNING,
    MQTT_STATE_DISCONNECT,
    MQTT_STATE_RECONNECT,
    MQTT_STATE_WAIT_RETRY
};


