name: utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  paxlog:
    path: /home/pomo/git/dart-packages/paxlog
  latlong2: ^0.9.1
  crc32_checksum: ^0.0.2

dev_dependencies:
#  lints: ^5.1.0
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  dio: ^5.7.0
  google_mobile_ads: ^5.3.0
  url_launcher: ^6.3.1
  path_provider: any
  shared_preferences: any
  provider: ^6.1.2
  intl: ^0.17.0

