name: stcp
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  basic_utils: ^5.7.0
  paxlog:
    path: /home/pomo/git/dart-packages/paxlog/
  the_tcp_messaging:
    path: ../local-packages/the_tcp_messaging
  the_secure_comm:
    path: /home/pomo/git/dart-packages/the_secure_comm
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2
  pointycastle: ^3.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
