[package]
name = "stcp-v2-mqtt-proxy"
version = "0.2.0"
edition = "2024"
autobins = false

[dependencies]
stcp-kernel-core = { path = "../../../module/rust", features = ["userspace"] }
libc = "0.2"
rand_core = { version = "0.6", features = ["getrandom"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }
chacha20poly1305 = "0.10"

[[bin]]
name = "stcp-proxy"
path = "bin/stcp_proxy.rs"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
