# =========================================================
# MINIMAL SYSTEM
# =========================================================

CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# =========================================================
# LOGGING (minimal)
# =========================================================

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_IMMEDIATE=y

# =========================================================
# LTE LINK CONTROL DEBUG
# =========================================================
CONFIG_LTE_LINK_CONTROL_LOG_LEVEL_DBG=y

# =========================================================
# AT MONITOR (optional but useful)
# =========================================================

CONFIG_AT_MONITOR=y
CONFIG_AT_MONITOR_LOG_LEVEL_DBG=y

# =========================================================
# MODEM / Nordic
# =========================================================

CONFIG_NRF_MODEM_LIB=y
CONFIG_MODEM_INFO=y

# =========================================================
# MODEM / Link control
# =========================================================
CONFIG_LTE_LINK_CONTROL=y
CONFIG_LTE_LINK_CONTROL_LOG_LEVEL_DBG=y

# =========================================================
# NETWORK
# =========================================================

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y

# =========================================================
# Stacks
# =========================================================
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=2048

CONFIG_MAIN_STACK_SIZE=10240
CONFIG_HEAP_MEM_POOL_SIZE=10240

#CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=4096
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

CONFIG_AT_MONITOR_HEAP_SIZE=4096


# =========================================================
# DNS
# =========================================================

CONFIG_DNS_RESOLVER=y

# STCP
CONFIG_STCP=y
CONFIG_STCP_DEBUG=y
CONFIG_STCP_DEBUG_LATENCY=n
CONFIG_STCP_SELFTEST=n

# STCP / Watchdog
CONFIG_STCP_WATCHDOG_ENABLE=n
CONFIG_STCP_WATCHDOG_MAX_TIMEOUT=1200
CONFIG_STCP_WATCHDOG_CHECK_INTERVAL=15

# STCP / AES
CONFIG_STCP_AES_BYPASS=n

# STCP / MQTT
CONFIG_MQTT_LIB=y
CONFIG_MQTT_LIB_STCP=y

# STCP / Status monitor & Statistics
CONFIG_STCP_STATUS_MONITOR=y
CONFIG_STCP_STATUS_MONITOR_STATISTICS=y
CONFIG_STCP_STATUS_MONITOR_LOG_INTERVAL=5

# STCP ISP's APN name
CONFIG_STCP_LTE_APN_NAME="internet"

# STCP networking: Where to connect
CONFIG_STCP_CONNECT_TO_HOST="lja.fi"
CONFIG_STCP_CONNECT_TO_PORT=7777


# STCP / testing
CONFIG_STCP_TESTING=y
# Sets debuggin on IF this is Y or if not then default is STCP_DEBUG setting
CONFIG_STCP_TESTING_LOG=y

# Disables testing debugs completely.
CONFIG_STCP_TESTING_LOG_COMPLETELY_OFF=n

CONFIG_STCP_TESTING_PEER_HOSTNAME_TO_CONNECT="lja.fi"
CONFIG_STCP_TESTING_PEER_PORT_TO_CONNECT=7777
# strftime format string 
CONFIG_STCP_TESTING_PAYLOAD_FORMAT="TErveppä terve! %Y-%m-%d %H:%M:%S ..."

# Testing mode 
CONFIG_STCP_TESTING_MODE=2

# Date-support for nice payload generation
# if user needs
CONFIG_DATE_TIME=y

# Power saving mode (=n)
CONFIG_LTE_PSM_REQ=n

# optimisations here
CONFIG_NET_BUF_RX_COUNT=8
CONFIG_NET_BUF_TX_COUNT=8
CONFIG_NET_PKT_RX_COUNT=4
CONFIG_NET_PKT_TX_COUNT=4
CONFIG_NET_MAX_CONTEXTS=4
CONFIG_NET_NATIVE=y
CONFIG_NET_OFFLOAD=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_LOG=n
CONFIG_NET_TCP_LOG_LEVEL_OFF=y
CONFIG_NET_UDP_LOG_LEVEL_OFF=y

