#!/bin/bash
MB=${1:-16}
BYTES=$((MB * 1024 * 1024))

echo "Scanning Git blobs larger than ${MB} MiB..."

git rev-list --objects --all |
    git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
    awk -v limit="$BYTES" '$1=="blob" && $3 > limit {printf "%.1f MiB\t%s\n", $3/1048576, $4}' |
    sort -nr
