name: the_tcp_messaging
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  paxlog:
    path: ../paxlog/
  the_secure_comm:
    path: ../the_secure_comm
  stcp:
    path: ../../src/stcp
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2

