CONFIG_STCP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=n
CONFIG_NET_NATIVE=y
CONFIG_NET_NATIVE_IP=y
CONFIG_NET_NATIVE_IPV4=y
CONFIG_NET_NATIVE_TCP=y
CONFIG_NET_NATIVE_UDP=y
CONFIG_NET_ARP=y
CONFIG_STCP_TRACE_WIRE=n
CONFIG_STCP_TRACE_EVENTS=n
CONFIG_STCP_TRACE_ALLOC=n
CONFIG_STCP_TRACE_CRYPTO=n
